#!/usr/bin/with-contenv sh

if [ -z "$RCLONE_REMOTE" ]; then
  echo "Error: RCLONE_REMOTE environment variable was not passed to the container."
  exit 1
fi

if [ ! -f /rclone/.rclone.conf ]; then
  echo "Error: /rclone/.rclone.conf does not exist. You have to pass it from the host."
  exit 1
fi

mount_command="rclone mount --config=/rclone/.rclone.conf --allow-other --log-level INFO --log-file /rclone/rclone.log --rc $RCLONE_OPTIONS $RCLONE_REMOTE RCLONE_REMOTE_MOUNT"

echo "Executing mount rclone => $mount_command"
exec s6-setuidgid abc $mount_command
