#!/usr/bin/with-contenv sh

if [ ! -f /rclone/.rclone.conf ]; then
  echo "Error: /rclone/.rclone.conf does not exist. You have to pass it from the host."
  exit 1
fi

mount_command="rclone mount --config=/rclone/.rclone.conf --cache-dir /home/abc/.cache/rclone/ --allow-other $RCLONE_OPTIONS $RCLONE_CACHE: /rclone/cloud"

echo "Executing => $mount_command"
exec s6-setuidgid abc $mount_command

