#!/usr/bin/with-contenv sh

CLOUDPLOW_CONFIG="/opt/cloudplow/config.json"

echo "Waiting mergerfs mount..."
while [ 0 -eq `ps -ef | grep abc | grep mergerfs | wc -l` ]; do
  sleep 1
done
echo "Found mergerfs mount done."

if [ ! -f $CLOUDPLOW_CONFIG ]; then
  echo "First run initializing cloudplow..."
  exec s6-setuidgid abc cloudplow run
  cat $CLOUDPLOW_CONFIG
  exec s6-setuidgid abc jq .core.rclone_binary_path="\"/usr/bin/rclone\"" $CLOUDPLOW_CONFIG > tmp.$$.json && mv tmp.$$.json $CLOUDPLOW_CONFIG
  exec s6-setuidgid abc jq .core.rclone_config_path="\"/rclone/.rclone.conf\"" $CLOUDPLOW_CONFIG > tmp.$$.json && mv tmp.$$.json $CLOUDPLOW_CONFIG
  echo "aaaa"
  cat $CLOUDPLOW_CONFIG
  exit 1
fi

echo "Executing cloudplow for remote upload"
exec s6-setuidgid abc cloudplow run
