#!/usr/bin/with-contenv sh

exec s6-svwait abc -u /etc/services.d/10-mount-rclone
rclone rc vfs/refresh recursive=true

mount_command="mergerfs -f -o async_read=false,use_ino,allow_other,auto_cache,func.getattr=newest,category.action=all,category.create=ff /rclone/local=RW:/rclone/remote=RO /rclone/data"

echo "Executing mount mergerfs => $mount_command"
exec s6-setuidgid abc $mount_command
