#!/usr/bin/with-contenv sh

if [ -z "$RCLONE_REMOTE_MOUNT" ]; then
  echo "Error: RCLONE_REMOTE_MOUNT environment variable was not passed to the container."
  exit 1
fi

cache-dir

mount_command="rclone mount --config=/config/.rclone.conf --cache-dir ~/ --allow-other $RCLONE_MOUNT_OPTIONS $RCLONE_REMOTE_MOUNT /data"

echo "Executing => $mount_command"
exec s6-setuidgid abc $mount_command
