#!/usr/bin/with-contenv sh

if [ -z "$RCLONE_REMOTE_MOUNT" ]; then
  echo "Error: RCLONE_REMOTE_MOUNT environment variable was not passed to the container."
  exit 1
fi

if [ ! -f /config/.rclone.conf ]; then
  echo "Error: /config/.rclone.conf does not exist. You have to pass it from the host."
  exit 1
fi

cp /config/.rclone.conf /home/abc/.rclone.conf
chown abc:abc /home/abc/.rclone.conf

mount_command="rclone mount --config=/home/abc/.rclone.conf --cache-dir ~/.cache/rclone/ --allow-other $RCLONE_MOUNT_OPTIONS $RCLONE_REMOTE_MOUNT /data"

echo "Executing => $mount_command"
exec s6-setuidgid abc $mount_command
